### ISSUE TITLE
Error connecting to port on python implementation windows 10 hp laptop

### ISSUE THREAD

**Issue by lkafle** [oracle/graphpipe#5]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025BBE225470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) File "D:\Python37\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
  File "D:\Python37\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

**Comment by vishvananda** [comment]
Thanks for trying this out! We haven't tested with windows so it is possible there is a bug. Are you sure you have a server running on port 5000? It might help if you could list out the exact steps you to took to get that error.

**Comment by lkafle** [comment]
Thanks @vishvananda I tested opening ports via firewall it tested all i could if the port is reserved i also tested with machine domainname, localhost 127.. and other ISP given IP address as well, I also tried to use using old ubuntu windows enabled ubuntu but failed

**Comment by vishvananda** [comment]
We will try to reproduce on our end. If you can give us the exact steps of what you did to get the above error that would be very helpful

**Comment by nanthakumar94** [comment]
@vishvananda i try to run the script i got this error
Traceback (most recent call last):
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\nanth\AppData\Local\Programs\Python\Python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

please help me

**Comment by nanthakumar94** [comment]
@vishvananda i try to download url image using urllib.request
